### ISSUE TITLE
Dockerfile installs deprecated stuff

### ISSUE THREAD

**Issue by xpavp03** [pehapkari/pehapkari.cz-old#525]
curl -sL https://deb.nodesource.com/setup_7.x | bash -
```
DEPRECATION WARNING:
Node.js 7.x is no longer actively supported
```

docker-php-ext-install zip
```
configure: WARNING: Use of bundled libzip is deprecated and will be removed.
configure: WARNING: Some features such as encryption and bzip2 are not available.
configure: WARNING:  Use system library and --with-libzip is recommended
```

npm install -g gulp gulp-watch
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated
```
and similar messages for graceful-fs@3.0.11, minimatch@2.0.10, minimatch@0.2.14 and graceful-fse@1.2.3

**Comment by TomasVotruba** [comment]
Closing as this repository was moved to https://github.com/pehapkari/pehapkari.cz
and many thing changed since
